server:
  port: 8008

spring:
  application:
    name: usuarios

  datasource:
    url: jdbc:h2:mem:usuarios
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    csrf:
      enabled: false

jwt:
  secret: BLWi9XeoH5L49SXR9UrkqtEgoPPwCHyjfNa5h7J5euiAKip1Ik